version: '3.8'

services:
  rabbitmq:
    container_name: "rabbitMq"
    image: rabbitmq:3.8-management-alpine
    ports:
      - "5672:5672"
      - "7280:7280"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS= password
